### ISSUE TITLE
changable PIDFile path

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#10]
<a href="https://github.com/Andrwe"><img src="https://avatars.githubusercontent.com/u/231689?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Andrwe](https://github.com/Andrwe)**
_Saturday Jan 25, 2014 at 16:23 GMT_
_Originally opened as https://github.com/palavatv/palava-machine/issues/5_

---

Hi,

it should be possible to specify the path of the PIDFile while running in daemon-mode.

If you run the daemon as non-root-user the path of the daemon-binary has to be writeable for this user otherwise the daemon doesn't start.
This means currently you aren't able to install this application in a default linux FHS because the PIDFile would be created in /usr/bin/.

A quick fix I'm using is to add the following lines to the parameters of "Daemons.run":
  dir_mode: :normal,
  dir: "/var/run/palava-machine/",

This approach isn't quite portable as the path has to be created by the installation process.

Regards,
Andrwe

**Comment by janlelis** [comment]
machine is not part of default palava stack anymore. please use machine repo for issues
