### ISSUE TITLE
add screen sharing

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#12]
<a href="https://github.com/thkoch2001"><img src="https://avatars.githubusercontent.com/u/94641?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thkoch2001](https://github.com/thkoch2001)**
_Friday Jan 03, 2014 at 10:51 GMT_
_Originally opened as https://github.com/palavatv/palava-portal/issues/2_

---

Support: 
- Chrome 26 with "Enable screen capture support in getUserMedia()" turned on in about:flags or --enable-usermedia-screen-capturin flag set.
- firefox 27? https://bugzilla.mozilla.org/show_bug.cgi?id=742832

more info:
- http://www.labnol.org/software/screen-sharing-apps/28305

Screencapture demos:
- https://simpl.info/screencapture
- https://html5-demos.appspot.com/static/getusermedia/screenshare.html
- https://github.com/muaz-khan/WebRTC-Experiment/tree/master/Pluginfree-Screen-Sharing site: https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/

**Comment by janlelis** [comment]
See https://github.com/palavatv/palava/issues/17
