### ISSUE TITLE
audio-only option

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#14]
<a href="https://github.com/Cathryne"><img src="https://avatars.githubusercontent.com/u/757323?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cathryne](https://github.com/Cathryne)**
_Sunday Jan 12, 2014 at 10:17 GMT_
_Originally opened as https://github.com/palavatv/palava-portal/issues/5_

---

It would be great to have audio only as a 3rd -- or [4th](https://github.com/palavatv/palava-portal/issues/2) ;-) -- option beside regular audio+video & video only. Thanks and greetings!

**Comment by farao** [comment]
This has been deployed a long time ago :-)
