### ISSUE TITLE
Browser incompatibilities

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#15]
<a href="https://github.com/ce6n"><img src="https://avatars.githubusercontent.com/u/1876214?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ce6n](https://github.com/ce6n)**
_Thursday Jan 30, 2014 at 12:08 GMT_
_Originally opened as https://github.com/palavatv/palava-portal/issues/7_

---

Some browser combinations did not work for me. I'll try to make a list:

| 1 | 2 | working? |
| --- | --- | --- |
| Firefox 26.0 (OSX 10.9.1) | Firefox 26.0 (Windows7) | no video / no sound |
| Chrome 32.0.1700.102 (OSX 10.9.1) | Firefox 26.0 (Windows7) | no video / no sound |
| Chrome 32.0.1700.102 (OSX 10.9.1) | Chrome 32.0.1700.99 (Android) | flawless |
| Firefox 26.0 (OSX 10.9.1) | Chrome 32.0.1700.99 (Android) | no video |
| Firefox 26.0 (Windows7) | Chrome 32.0.1700.99 (Android) | no video / no sound |
| Firefox 26.0 (OSX 10.9.1) | Chrome 32.0.1700.102 (OSX 10.9.1)) | no video |

Maybe this helps

**Comment by janlelis** [comment]
stale
