### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#18]
<a href="https://github.com/phipse"><img src="https://avatars.githubusercontent.com/u/1436211?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [phipse](https://github.com/phipse)**
_Friday Apr 18, 2014 at 11:11 GMT_
_Originally opened as https://github.com/palavatv/palava-portal/issues/12_

---

Translate the instructions
a) depending on the browser language 
b) display english+browser language

Translate the HowTo.

**Comment by janlelis** [comment]
[palava-portal has been replaced by palava-web!](https://github.com/palavatv/palava-web)

(has full localization en / de)
