### ISSUE TITLE
Audio only option

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#22]
<a href="https://github.com/ianb"><img src="https://avatars.githubusercontent.com/u/44390?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianb](https://github.com/ianb)**
_Monday Mar 03, 2014 at 19:42 GMT_
_Originally opened as https://github.com/palavatv/palava-hq/issues/1_

---

(Not sure if this is the best place to ask about features on https://palava.tv/)

Right now there's audio+video, and video only options, but no audio only option.

**Comment by haslinger** [comment]
If you talk about your own installation, I had success to get audio only with the demo script and setting
```
session.init({
  identity: new palava.Identity({ userMediaConfig: { audio: true, video: false } }),
  options: { stun: 'stun:your.domain.here', joinTimeout: 500 }
})

**Comment by farao** [comment]
This has been deployed a long time ago :-)
