### ISSUE TITLE
Newbie socket error

### ISSUE THREAD

**Issue by haslinger** [palavatv/palava#25]
First off: Palava is absolutely awesome! Thanks for your hard work!

I'm trying to connect to a locally installed palava-server, with the demo script pointing to my development machine ip 
```
channel = new palava.WebSocketChannel('wss://10.0.0.111:4233')
#...
options: { stun: 'stun:10.0.0.111', joinTimeout: 500 }
```
and I'm getting
```bash
2015-01-27 17:34:43 | Starting RTC Socket Server on port 4233
*** Socket Error *** EventMachine::WebSocket::HandshakeError ***
Invalid HTTP header: Could not parse data entirely
```

Browser console tells me 
```
WebSocket connection to 'wss://10.0.0.111:4233/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
which is consistent.
When I'm not trying to use my own server and go with the Palava ones, it works nicely.

It seems, I'm doing something completely wrong here with the server ... any ideas?
Do I have to use a proxy in front? Is there a way to use Apache instead of Nginx for this?

**Comment by thammi** [comment]
`wss://` is for secure web sockets which have TLS encryption. Use `ws://` URLs or add TLS encryption using a reverse proxy.

**Comment by haslinger** [comment]
Omg! And works! Thank you, @thammi!
