### ISSUE TITLE
What has to be opened on server's firewall?

### ISSUE THREAD

**Issue by haslinger** [palavatv/palava#26]
I deployed palava to a test server and it somehow work, but connections get lost. 
Now I see that the firewall on the server blocks udp packets. 
Are there any patterns what I should allow regarding tcp or do I have to allow udp in general?

I think this aspect would also be nice to have some documentation on. (I didn't find any ....)
Cheers and keep up the great work!
Stefan

**Comment by thammi** [comment]
The server is only using the HTTP(S) and WebSocket protocols which are both TCP based. To get the best user experience use a reverse proxy to provide both services on port 80.

The actual audio/video connection is established directly between the browsers. The server only passes the messages which are needed to established the connection through the WebSocket connections. Establishing this connection is hindered by the Firewall/Router/NAT/Provider/... of both peers. WebRTC uses STUN (enabled by default in palava) and TURN (you have to add a server to your configuration) to get through. Once the connection is established it is nearly always stable in my experience (ignoring bandwidth problems).

**Comment by thammi** [comment]
I just looked through the code and it seems there is no default option for the stun server. See [here](https://github.com/palavatv/palava-portal/blob/master/source/assets/js/app/controllers/palava_controller.coffee.erb#L52) on how to set it.

If you are using your own STUN server that might be the UDP traffic you see. The default port is 3478 UDP and TCP.

**Comment by haslinger** [comment]
Reading through my own question - so unprecise, sorry. Thanks for your patience and answers! Your second answer nailed it. No more firewall blocking log messages. 3478 UDP + TCP are the only ports I was missing.
Interestingly the connections are lost despite that.

When I'm using palava.tv everything is rock solid (tested yesterday pair programming for > 1 hour), several machines, browsers, even arm + i86. Rock solid.

When I'm using my own installation losing connection after 1-2 min. 
The installation is publicly available at http://www.informatom.com/webpages/videochat (no password whatsover) and I based it off the minimal [example](https://gist.github.com/thammi/9005857).

Just one warning in the Javascript console ('webkitURL' is deprecated. Please use 'URL' instead.) But that warning is also there with palava.tv as well.

Also, when I use palava.tv and connect 10mins later, they find each other like a charm, within under 1s. In my own install, I have to connect within seconds, otherwise no connection. I must be doing something fundamentally wrong...

Going to give it another debugging retry tonight....

**Comment by thammi** [comment]
Do you have a STUN server installed at 'palava.informatom.com'? My [test utility](https://github.com/palavatv/palava-utils/blob/master/stuncheck) is not able to contact a STUN server there. If you do not have your own STUN server you can use a [free one](https://gist.github.com/zziuni/3741933).

There might be a race condition with the connection being established through the local network and the STUN error later disconnecting it.

**Comment by haslinger** [comment]
You nailed it again. Thank you for your support! And thanks for the link to the test tool, which will be handy when I roll my own STUN server.

**Comment by haslinger** [comment]
Meanwhile I have installed my own stun/turn server and your test script was invaluable, because the stun test tool/client from Ubuntu gives no useful output (your script triggered me to debug thoroughly).
The stun/turn-server is palava.informatom.com and is available at 93.189.25.83 and 93.189.25.84.

But unfortunately as well as will the public servers (I tried 3 of them), I still lose the connections as described before (only connecting within seconds, lose connection mostly within 1-2 minutes). 
Sorry to be so sticky...

I have also set up a page with audio only (http://www.informatom.com/webpages/audiochat).
Same behavior here. But I learned one more thing:
It is one side that looses connection and gets that(so the element disappears) while the other doesn't get the notice (element stays there).

( I see, you are not too far from me ... whenever in Vienna, give me a shout out and I'll invite you for lunch or whatever.)

**Comment by thammi** [comment]
The WebSocket disconnects after some time. The most probable cause for this is that your nginx is timing out the connection. Try adding something like this to your configuration:

    proxy_read_timeout 86400;

PS: I tested this using [wscat](https://www.npmjs.com/package/wscat). Just connect to your signaling server and wait a minute. If you want to pretend to be a client send something like `{"event":"join_room","room_id":"informatom-1","status":{"user_agent":"chrome"}}`. After that you should get all join events.

**Comment by haslinger** [comment]
Yes. It is. That fixes it (just looked it up: default is 60s).
Running already for 15min with 4 clients rock solid. And I can reconnect whenever I like.

Thanks for pointing me to wscat! Super handy for debugging.
Your support was absolutely awesome. If you can think of a way I can give back, please tell me!
