### ISSUE TITLE
Add Firefox 44.0.2 to supported browsers

### ISSUE THREAD

**Issue by nightvisi0n** [palavatv/palava#29]
I have the latest Firefox (`44.0.2`) installed, but https://palava.tv is warning me that me browser is not supported and i should install `Mozilla Firefox 22 or above`.  
I think this requirement is clearly fulfilled and i assume this is an error in the code ;-)

**Comment by farao** [comment]
Hm, that's strange. Works in Firefox 44.0.2 on Arch Linux for me. palava actually doesn't check for the browser version but for the existance of the RTCPeerConnection function that is part of the Javascript API. Could you please verfiy in a web console (press F12 in Firefox) that one of the following is present: window.PeerConnection or window.webkitPeerConnection00 or window.mozRTCPeerConnection ? In my Firefox 44 it's window.RTCPeerConnection.
