### ISSUE TITLE
palava.tv kicks connection after a minute (includes a work around)

### ISSUE THREAD

**Issue by guentherlause** [palavatv/palava#32]
Hi there,

a local signaltower installation as well as the central palava.tv server kicks all clients after a minute. Maybe related to issue #26 (look for the wscat example). On client side I've used firefox on win, linux, mac, seems chrome has some issues too nowadays.

If I send artificial traffic to the web socket every 30 seconds with wscat the session will survive on palava.tv as well on my local installation! 

Example for palava.tv site, room testxyz123, bash cli:

while true; do wscat -c wss://machine.palava.tv -x '{"event":"join_room","room_id":"testxyz123","status":{"user_agent":"chrome"}}';echo;echo;date; sleep 30;done;

Is this an issue with signaltower (is there a configuration option?) or a new default for the browsers or just a deprecated js-api on client side?
Maybe it's easy to fix  palava-client to send a ping from time to time.

btw: thanks a lot for palava - I've used the  (now deprecated) docker container for years!

Andreas

**Comment by farao** [comment]
Hi Andreas,

thanks - the new version of the websocket library in the signal tower suddenly had a timeout of 60s - and we didn't extend it. Should be fixed now!
