### ISSUE TITLE
Resolve WebRTC API deprecation warnings

### ISSUE THREAD

**Issue by farao** [palavatv/palava#34]
Firefox 65 shows the following WebRTC API deprecation warnings:

- [x] RTCIceServer.url is deprecated! Use urls instead.
- [x] onaddstream is deprecated! Use peerConnection.ontrack instead.
- [x] RTCPeerConnection.getLocalStreams/getRemoteStreams should not be used anymore. Use RTCPeerConnection.getSenders/getReceivers instead

**Comment by janlelis** [comment]
Resolved in latest client
