### ISSUE TITLE
Switch to other available video when peer leaves

### ISSUE THREAD

**Issue by KopierKatze** [palavatv/palava#35]
When a peer leaves and their video is displayed on the left side ("stage"), their video image freezes. Instead, it should automatically switch to another available video stream.

**Comment by KopierKatze** [comment]
It seems this bug is hard to reproduce. Sometimes, when a peer leaves, their video stays visible (both on stage and in the list of peers on right side) when they leave and the video shows the last frame.

**Comment by janlelis** [comment]
[palava-portal has been replaced by palava-web!](https://github.com/palavatv/palava-web)
