### ISSUE TITLE
Audio Only Mode

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#5]
<a href="https://github.com/ax3l"><img src="https://avatars.githubusercontent.com/u/1353258?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ax3l](https://github.com/ax3l)**
_Wednesday Jul 23, 2014 at 11:17 GMT_
_Originally opened as https://github.com/palavatv/palava-client/issues/8_

---

Hey guys,

thanks for the great software!
One minor: for quite bad connections It would be great if one could generally use an "Audio only" mode :)

**Comment by farao** [comment]
Done a long time ago ;-)
