### ISSUE TITLE
No man pages for palava-machine and palava-machine-daemon

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#8]
<a href="https://github.com/ajaissle"><img src="https://avatars.githubusercontent.com/u/2892835?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ajaissle](https://github.com/ajaissle)**
_Thursday Jan 16, 2014 at 13:27 GMT_
_Originally opened as https://github.com/palavatv/palava-machine/issues/3_

---

Hi,
please provide man pages for the following executables:
    palava-machine
    palava-machine-daemon

 Each executable in standard binary directories should have a man page.

**Comment by janlelis** [comment]
machine is not part of default palava stack anymore. please use machine repo for issues
