### ISSUE TITLE
redis_address is not used for stats

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#9]
<a href="https://github.com/Andrwe"><img src="https://avatars.githubusercontent.com/u/231689?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Andrwe](https://github.com/Andrwe)**
_Saturday Jan 25, 2014 at 12:35 GMT_
_Originally opened as https://github.com/palavatv/palava-machine/issues/4_

---

Hi,

in jobs/export_stats_job.rb you define initialize() with two parameters "redis_address" and "mongo_address" which can be given via command line.

But you don't use redis_address to start the redis-connection.
Instead you use hardcoded localhost:6379.

Thus you can't change the redis-server configuration withour losing the stats-mechanism.

The call should be changed to something like:
EM::Hiredis.connect "redis://#{@redis_address}/#{@redis_db}" (used in manager.rb)

Regards,
Andrwe

**Comment by janlelis** [comment]
See https://github.com/palavatv/palava-machine/pull/6

**Comment by janlelis** [comment]
machine is not part of default palava stack anymore. please use machine repo for issues
